FROM node:12-bullseye

RUN apt-get update && apt-get install -y -q --no-install-recommends ca-certificates curl build-essential libsodium-dev libboost-system-dev git


# Clone foundation server
RUN cd / && git clone https://github.com/blinkhash/foundation-server.git /foundation-server

# Build foundation server
RUN cd /foundation-server && npm i

WORKDIR /foundation-server
CMD [ "npm", "run", "start" ]