FROM node:12-bullseye

RUN apt-get update && apt-get install -y -q --no-install-recommends ca-certificates curl build-essential libsodium-dev libboost-system-dev git


# Clone foundation server
RUN git clone https://github.com/blinkhash/foundation-v2-server.git /foundation-server 

WORKDIR /foundation-server

# Build foundation server
RUN npm i 

# Install foundation server templates
RUN npm install --save foundation-v2-bitcoin 

CMD [ "npm", "run", "start" ]